# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:
#    url: jdbc:sqlite:C:\Files\IntelliJ\SQLite\SQLiteDatabaseBrowserPortable\Data\test.db
#    driverClassName: org.sqlite.JDBC

    url: jdbc:mysql://127.0.0.1:3306/test
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate.ddl-auto: update

  mail:
      default-encoding: UTF-8
      host: smtp.gmail.com
      username: radu.todirica07@gmail.com
      password: jsutpocvneunohjp
      port: 587
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
      protocol: smtp
      test-connection: false

#  jpa:
#    show-sql: true
#    hibernate.ddl-auto: update
#    database-platform: com.enigmabridge.hibernate.dialect.SQLiteDialect

jwt:
  header: Authorization
  secret: /wKLE9vxudoWuZMwKHV63YCpADquNgt/K+HLPwfw0q4=
  expiration: 604800

route:
  register: register
  authentication:
    path: auth
    refresh: refresh
  profile:
    userprofile: getProfile
    saveprofile: saveProfile
  establishment:
    getestablishment: getEstablishment
    getestablishments: getEstablishments
    getmyestablishments: getMyEstablishments
    createestablishment: createEstablishment
    updateestablishment: updateEstablishment
    deleteestablishment: deleteEstablishment

    getcomment: getComment
    getcomments: getComments
    createcommment: createComment
    updatecomment: updateComment
    deletecomment: deleteComment

    getfeature: getFeature
    getfeatures: getFeatures
    createfeatures: createFeatures
    updatefeatures: updateFeatures
    deletefeatures: deleteFeatures

    getmeal: getMeal
    getmeals: getMeals
    createmeal: createMeal
    updatemeal: updateMeal
    deletemeal: deleteMeal

    listpriceestablishment: getPriceEstablishment
    createpriceestablishment: createPriceEstablishment
    updatepriceestablishment: updatePriceEstablishment
    deletepriceestablishment: deletePriceEsablishment

    listqualityestablishment: getQualityEstablishment
    createqualityestablishment: createQualityEstablishment
    updatequalityestablishment: updateQualityEstablishment
    deletequalityestablishment: deleteQualityEsablishment

    getmyestablishmentraiting: getMyEstablishmentRaiting
    addestablishmentraiting: addEstablishmentRaiting
    editestablishmentraiting: editEstablishmentRaiting
    removeestablishmentraiting: removeEstablishmentRaiting


  category:
    getcategory: getCategory
    getcategories: getCategories
    createcategory: createCategory
    updatecategory: updateCategory
    deletecategory: deleteCategory
  product:
    getproduct: getProduct
    getproducts: getProducts
    createproduct: createProduct
    updateproduct: updateProduct
    deleteproduct: deleteProduct
  ingredient:
    getingredient: getIngredient
    getingredients: getIngredients
    createingredient: createIngredient
    updateingredient: updateIngredient
    deleteingredient: deleteIngredient



logging:
  level:
    org.springframework:
      security: DEBUG