# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:
    #url: jdbc:mysql://dbdev101.ccx7hdurz6w7.eu-west-1.rds.amazonaws.com/devtest102
    url: jdbc:mysql://localhost:3306/test_schema
    driverClassName: com.mysql.jdbc.Driver
    username: user_1920
    password: kinetix1920

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate.ddl-auto: update

jwt:
  header: Authorization
  secret: /wKLE9vxudoWuZMwKHV63YCpADquNgt/K+HLPwfw0q4=
  expiration: 604800

route:
  register: register
  authentication:
    path: auth
    refresh: refresh
  profile:
    userprofile: getProfile
    saveprofile: saveProfile
  restaurants:
    listrestaurants: getRestaurants
    ceraterestaurant: createRestaurant
    updaterestaurant: updateRestaurant
  menu:
    getmenus: getMenus
    createmenu: createMenu
    updatemenu: updateMenu

logging:
  level:
    org.springframework:
      security: DEBUG